---
title: "Untitled"
output: html_document
date: "2024-03-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(RSQLite)
library(dplyr)
library(tidyr)
library(ggplot2)
```

```{r}
schema_db <- RSQLite::dbConnect(RSQLite::SQLite(), "ECommerce.db")
```

```{r}
# Read data
table_name <- dbListTables(schema_db)
tables <- list()
for (name in table_name){
  tables[[name]] <- dbReadTable(schema_db, name)
}
```

```{r}
joint_in_table <- tables[["joint_in"]]
joint_order_table <- tables[["joint_order"]]
```

```{r}
# Payment methods
transaction_table <- tables[["transaction"]]
payment_plot <- ggplot(transaction_table, aes(x = payment_method))+
  geom_bar(fill = 'indianred3') +
  labs(x = "Payment Method", y = "Count")

# Save the plot
ggsave("payment.jpeg", plot = payment_plot, width = 10, height = 6, dpi = 300)

```

```{r}
# Best sellers for each category
product_table <- tables[["product"]]
category_table <- tables[["category"]]

bsec <- product_table %>% 
  left_join(joint_in_table, by = "product_id") %>%
  left_join(category_table, by = "category_id") %>%
  left_join(joint_order_table, by = "product_id")

best_sellers <- bsec %>%
  group_by(category_name, product_name) %>%
  summarise(total_quantity = sum(quantity), .groups = 'drop') %>%
  group_by(category_name) %>%
  arrange(desc(total_quantity)) %>%
  slice(1) %>% 
  ungroup()

bests <- ggplot(best_sellers) +
  geom_bar(aes(x = product_name, y = total_quantity, fill = category_name), 
           stat = "identity") + 
  labs(x = "Products", y = "Quantity") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Save the plot
ggsave("bestsellers.jpeg", plot = bests, width = 10, height = 6, dpi = 300)

```

```{r}
# Which category is the most popular

category_table <- tables[["category"]]
product_table <- tables[["product"]]
customer_table <- tables[["customer"]]
joint_in_table <- tables[["joint_in"]]

# Step 1: Join the product and category tables using the joint table
product_category_join <- joint_in_table%>%
  inner_join(product_table, by = "product_id") %>%
  inner_join(category_table, by = "category_id")

# Step 2: Aggregate the data to count occurrences of each category
category_counts <- product_category_join %>%
  group_by(category_name) %>%
  summarise(count = n()) %>%
  arrange(desc(count))

# Step 3: Print or visualize the results to identify the most popular category
most_popular_category <- category_counts$category_name[1]
print(paste("The most popular category is:", most_popular_category))


top_cat <- ggplot(category_counts, aes(x = reorder(category_name, -count), y = count)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(x = "Category", y = "Number of Products", title = "Popularity of Categories") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_flip()

# Save the plot
ggsave("top_category.jpeg", plot = top_cat, width = 10, height = 6, dpi = 300)
```

```{r}
# Final Price of Orders Distribution
tot_price <- 'SELECT final_price, order_detail_id FROM final_price_of_order'
view_tot <- dbGetQuery(schema_db, tot_price)
view_tot <- as_tibble(view_tot)

transaction_table <- tables[["transaction"]]
transaction_table <- left_join(transaction_table, view_tot, by = 'order_detail_id')
basket <- ggplot(transaction_table, aes(final_price, fill = payment_method)) +
  geom_histogram(binwidth = 2000) +
  labs(title = 'Distribution of Orders based on Payment Method', x = 'Price', y = 'Frequency') 

# Save the plot
ggsave("basket_price.jpeg", plot = basket, width = 10, height = 6, dpi = 300)
```

```{r}
# Top 20 customers 

```

```{r}
# which product has the highest rating in each category
```