name: ETL Workflow for Group 10

on:
#  schedule:
#    - cron: '0 */3 * * *' # Run every 3 hours
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/lockfile') }}
          restore-keys: |
            ${{ runner.os }}-r-
      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          Rscript -e 'install.packages(c("ggplot2", "dplyr", "readr", "tidyr", "RSQLite", "fakir", "charlatan", "generator"))'
      - name: Execute R script to load first phase of the data to database
        run: |
          Rscript R/First_Phase_Data_Load.R
      - name: Execute R script to load update the database with new entry (second data phase)
        run: |
          Rscript R/Second_Phase_Data_Load.R
      - name: Add files
        run: |
          git config --global user.email "kiranlyy@gmail.com"
          git config --global user.name "lyy"
      - name: Add modified files
        run: |
          git add .
      - name: Commit files
        run: |
          git commit -m "Add analysis results"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
            github_token: ${{ secrets.MY_TOKEN }}
            branch: main
